# Generated by Django 5.1 on 2024-08-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0003_alter_questions_options_tests_is_avaible"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tests",
            old_name="is_avaible",
            new_name="is_available",
        ),
    ]
