# Generated by Django 5.1 on 2024-08-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_rename_is_avaible_tests_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="question_text",
            field=models.CharField(
                default="Вопрос:", max_length=250, verbose_name="Вопрос"
            ),
        ),
    ]
