# Generated by Django 5.1 on 2024-08-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0005_alter_questions_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="test",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="tests.tests"
            ),
            preserve_default=False,
        ),
    ]
